# Generated by Django 3.2.9 on 2021-11-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='critical_hit_bonus_default',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Critical hit bonus default, %'),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='distance_default',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='environment_damage_default',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='max_damage_default',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='min_damage_default',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='usage_limit_default',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
