# Generated by Django 3.2.9 on 2021-11-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_auto_20211125_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectile',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='projectiletype',
            name='usage_limit_default',
        ),
        migrations.RemoveField(
            model_name='tanktype',
            name='max_projectiles',
        ),
    ]
