# Generated by Django 3.2.9 on 2021-11-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0004_auto_20211126_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectile',
            name='tank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectiles', to='battle.tank'),
        ),
    ]
