# Generated by Django 3.2.9 on 2021-12-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_alter_projectile_tank'),
    ]

    operations = [
        migrations.AddField(
            model_name='battletype',
            name='player_tanks_number',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
