# Generated by Django 3.2.9 on 2021-12-13 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0007_auto_20211209_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectile',
            name='name',
        ),
    ]
