# Generated by Django 3.2.9 on 2021-12-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0008_remove_projectile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectile',
            name='owner',
        ),
    ]
