# Generated by Django 3.2.9 on 2021-12-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0009_remove_projectile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='action_points',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='moving_points',
        ),
        migrations.RemoveField(
            model_name='tanktype',
            name='action_points_default',
        ),
        migrations.RemoveField(
            model_name='tanktype',
            name='fuel_default',
        ),
        migrations.RemoveField(
            model_name='tanktype',
            name='moving_points_default',
        ),
        migrations.AddField(
            model_name='projectile',
            name='fire_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='projectiletype',
            name='fire_price_default',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tank',
            name='moving_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tanktype',
            name='moving_price_default',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
