# Generated by Django 3.2.9 on 2021-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_auto_20211215_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
