# Generated by Django 3.2.9 on 2021-12-30 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_auto_20211224_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
