# Generated by Django 3.2.9 on 2022-01-12 09:02

import battle_of_chains.battle.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battle', '0012_alter_tank_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='sprite',
            field=models.ImageField(blank=True, null=True, upload_to=battle_of_chains.battle.models.upload_tank_path),
        ),
        migrations.AlterField(
            model_name='tank',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanks', to=settings.AUTH_USER_MODEL),
        ),
    ]
