# Generated by Django 3.2.9 on 2022-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0013_auto_20220112_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='basic_free_tank',
            field=models.BooleanField(default=False),
        ),
    ]
