# Generated by Django 3.2.9 on 2022-01-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0011_map_is_active'),
        ('battle', '0017_alter_country_options'),
    ]

    operations = [
    ]
