# Generated by Django 3.2.9 on 2022-01-17 09:05

import battle_of_chains.battle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0018_merge_0011_map_is_active_0017_alter_country_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='hull_sprite',
            field=models.ImageField(blank=True, null=True, upload_to=battle_of_chains.battle.models.upload_tank_path),
        ),
    ]
