# Generated by Django 3.2.9 on 2022-01-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('battle', '0019_tank_hull_sprite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.offer'),
        ),
    ]
