# Generated by Django 3.2.9 on 2022-01-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0020_tank_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tank',
            old_name='offer',
            new_name='origin_offer',
        ),
    ]
