# Generated by Django 3.2.9 on 2022-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0021_rename_offer_tank_origin_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_move', models.PositiveSmallIntegerField(default=45, verbose_name='Time to make move, seconds')),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
