# Generated by Django 3.2.9 on 2022-01-21 16:56

import battle_of_chains.battle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0022_battlesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battlesettings',
            name='menu_image',
        ),
        migrations.AddField(
            model_name='tank',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to=battle_of_chains.battle.models.upload_tank_path),
        ),
    ]
