# Generated by Django 3.2.9 on 2022-01-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0024_tank_date_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlesettings',
            name='tanks_per_page',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='Tanks per page in marketplace'),
        ),
    ]
