# Generated by Django 3.2.9 on 2022-01-28 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0025_battlesettings_tanks_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
    ]
