# Generated by Django 3.2.9 on 2022-01-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0026_tank_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlesettings',
            name='nft_ticker',
            field=models.CharField(default='TNKNFT', max_length=10, verbose_name='NFT contract Ticker'),
        ),
    ]
