# Generated by Django 3.2.9 on 2022-02-01 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0027_battlesettings_nft_ticker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battlesettings',
            options={'verbose_name': 'Global Settings', 'verbose_name_plural': 'Global Settings'},
        ),
        migrations.RemoveField(
            model_name='tank',
            name='block_chance',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='damage_bonus',
        ),
        migrations.RemoveField(
            model_name='tanktype',
            name='block_chance_default',
        ),
        migrations.RemoveField(
            model_name='tanktype',
            name='damage_bonus_default',
        ),
        migrations.AddField(
            model_name='tank',
            name='rebound_chance',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Rebound chance, %'),
        ),
        migrations.AddField(
            model_name='tanktype',
            name='rebound_chance_default',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Rebound chance default, %'),
        ),
    ]
