# Generated by Django 3.2.9 on 2022-02-02 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0029_tank_ammo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectile',
            name='fire_price',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='projectile',
            name='radius',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectile',
            name='ricochet_chance',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Ricochet chance, %'),
        ),
        migrations.AlterField(
            model_name='projectiletype',
            name='fire_price_default',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='projectiletype',
            name='radius_default',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectiletype',
            name='ricochet_chance_default',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Ricochet chance default, %'),
        ),
    ]
