# Generated by Django 3.2.9 on 2022-02-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0032_tanktype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
