# Generated by Django 3.2.9 on 2022-02-07 14:00

import battle_of_chains.battle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0035_alter_battle_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='background_file',
            field=models.FileField(null=True, upload_to=battle_of_chains.battle.models.upload_maps_path, verbose_name='Background'),
        ),
    ]
