# Generated by Django 3.2.9 on 2022-02-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0036_map_background_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlesettings',
            name='default_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Default user avatar'),
        ),
    ]
