# Generated by Django 3.2.9 on 2022-02-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0037_battlesettings_default_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
