# Generated by Django 3.2.9 on 2022-01-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0021_rename_offer_tank_origin_offer'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='base_tank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='battle.tank'),
        ),
    ]
