# Generated by Django 3.2.9 on 2022-02-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
