# Generated by Django 3.2.9 on 2022-02-16 10:21

import battle_of_chains.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_notifications_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=battle_of_chains.users.models.upload_user_path),
        ),
    ]
