# Generated by Django 3.2.9 on 2021-11-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False, verbose_name='Wallet address')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
        ),
    ]
