# Generated by Django 3.2.9 on 2021-12-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0010_auto_20211215_1439'),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Wallet address'),
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('for_sale', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('tank', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle.tank')),
            ],
        ),
    ]
