# Generated by Django 3.2.9 on 2021-12-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20211222_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(default='', max_length=50, verbose_name='Code')),
                ('rpc_url', models.URLField(verbose_name='RPC URL')),
                ('url_explorer', models.URLField(verbose_name='URL Explorer')),
            ],
        ),
        migrations.RemoveField(
            model_name='nft',
            name='for_sale',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='price',
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(default='', max_length=50)),
                ('address', models.CharField(blank=True, max_length=42, null=True, verbose_name='Contract address')),
                ('contract_url', models.URLField(blank=True, null=True, verbose_name='Contract URL')),
                ('deployed', models.BooleanField(default=False, verbose_name='Contract Deployed')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blockchain.network')),
            ],
        ),
        migrations.AddField(
            model_name='nft',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.contract'),
        ),
    ]
