# Generated by Django 3.2.9 on 2021-12-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_auto_20211224_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_definitions',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
