# Generated by Django 3.2.9 on 2021-12-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_contract_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='deployed',
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.network'),
        ),
    ]
