# Generated by Django 3.2.9 on 2021-12-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_auto_20211230_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='address',
            new_name='tx_hash',
        ),
    ]
