# Generated by Django 3.2.9 on 2021-12-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_rename_address_nft_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='tx_hash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
