# Generated by Django 3.2.9 on 2022-01-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_alter_nft_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blockchain.wallet'),
        ),
        migrations.CreateModel(
            name='BlockchainEvent',
            fields=[
                ('tx_hash', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Transaction Hash')),
                ('event', models.CharField(editable=False, max_length=100, verbose_name='Event name')),
                ('args', models.JSONField(editable=False)),
                ('block_number', models.PositiveIntegerField(default=1, editable=False)),
                ('timestamp', models.PositiveIntegerField(editable=False, null=True)),
                ('contract', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='blockchain.contract')),
            ],
        ),
    ]
