# Generated by Django 3.2.9 on 2022-01-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0009_auto_20220112_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_url',
        ),
    ]
