# Generated by Django 3.2.9 on 2022-02-01 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_remove_contract_contract_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainevent',
            name='tx_hash',
            field=models.CharField(editable=False, max_length=100, verbose_name='Transaction Hash', primary_key=False),
        ),
        migrations.AddField(
            model_name='blockchainevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='blockchainevent',
            unique_together={('tx_hash', 'event')},
        ),
    ]
