# Generated by Django 3.2.9 on 2022-02-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0011_auto_20220201_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='chain_id',
            field=models.CharField(default='', max_length=10, verbose_name='Chain ID, Hex string'),
        ),
    ]
