# Generated by Django 3.2.9 on 2022-02-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0012_network_chain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='ticker',
            field=models.CharField(default='', max_length=6, verbose_name='Network currency ticker'),
        ),
    ]
